seed: 12345

dataset_name: pol
dataset_split: 0
n_subsample: 0
subsample_seed: 0

kernel_name: matern32 # rbf, matern12, matern32, matern52
n_features: 2000

pretrained_init: False
noise_scale_init: 1.0
signal_scale_init: 1.0
length_scale_init: 1.0

noise_scale_min: 0.0 # set to 0.0 to disable clipping

n_iterations: 100
learning_rate: 1e-1

estimator_name: exact # exact, standard, pathwise
warm_start: False # True, False
n_samples: 64
pathwise_init: False

solver_name: chol # chol, cg, ap, sgd
rtol_y: 0.01 # mean
rtol_z: 0.01 # samples
max_epochs: 1000

batch_size: 500

log_wandb: False
log_verbose: True
log_metrics_exact: True
log_metrics_samples: True

checkpoint_interval: 0

wandb_project: null
wandb_entity: null
wandb_api_key: null
